lib/rubocop/ast/node/regexp_node.rb, spec/rubocop/ast/regexp_node_spec.rb
where option is 'o' + any other
=> [Fix rubocop-hq/rubocop-performance#106] Fix RegexpNode#to_regexp 

lib/rubocop/ast/node_pattern.rb
Example failure: https://github.com/rubocop-hq/rubocop-ast/pull/15/checks?check_run_id=724719610
=> Fix rubocop offense for redundant regex escape

lib/rubocop/ast/node_pattern.rb
Example failure: https://github.com/rubocop-hq/rubocop-ast/pull/18/checks?check_run_id=728073363
=> Fix regex offense reported by rubocop

CHANGELOG.md, lib/rubocop/ast/node/regexp_node.rb, spec/rubocop/ast/regexp_node_spec.rb
=> Add interpolation? check for RegexpNode

CHANGELOG.md, lib/rubocop/ast/node/regexp_node.rb, spec/rubocop/ast/regexp_node_spec.rb
As suggested by @bbatsov here:
https://github.com/rubocop-hq/rubocop/pull/8073#discussion_r433131081
=> Add RegexpNode regopt predicates

.github/workflows/rubocop.yml
This should actually fail because of #20
=> CI: add full run specs for main RuboCop repo

CHANGELOG.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
=> Add `argument_type?` method to make it easy to recognize argument nodes

CHANGELOG.md, docs/modules/ROOT/pages/node_pattern.adoc, lib/rubocop/ast/node_pattern.rb, spec/rubocop/ast/node_pattern_spec.rb
Used to be `node == param`.
For most classes, `===` is the same as `==`, and `==` is symmetric, so this has no impact, except for `Regexp`, `Class`, `Proc`, `Set`, `Range`, none of which can exist in the AST.
This opens many cool patterns though:
* `(hash <(pair (_ %1) $_)>...)` called with a regexp to match a symbol/string key
* `(send _ %1 ...)` called with `Set` of possible method names to match.
etc.
Thanks to @pirj for [bringing this to my attention](https://github.com/rubocop-hq/rubocop-rspec/pull/804)
=> NodePattern: Use `param === node` to match params.

CHANGELOG.md, lib/rubocop/ast/node/mixin/method_identifier_predicates.rb, spec/rubocop/ast/send_node_spec.rb
For context - https://github.com/rubocop-hq/rubocop-performance/pull/140/files#r439732580
This was already needed several times: [one](https://github.com/rubocop-hq/rubocop-performance/pull/140/files#diff-81a815a5887c41f8974ad4d9d34d11f7R41), [two](https://github.com/rubocop-hq/rubocop-performance/pull/127/files#diff-6e1da1392214a67f5b4f8919f93f9b20R31)
=> Add `enumerable_method?` for `MethodIdentifierPredicates`

CHANGELOG.md, lib/rubocop/ast.rb, lib/rubocop/ast/node/mixin/method_identifier_predicates.rb, spec/rubocop/ast/send_node_spec.rb
Moved from https://github.com/rubocop-hq/rubocop/pull/8155
For context https://github.com/rubocop-hq/rubocop-performance/pull/140/files#r439732580
Bullet number 4
=> Add helpers allowing to check whether the method is a nonmutating operator method or a nonmutating method

.github/workflows/rubocop.yml, lib/rubocop/ast/node.rb
There are cases where it won't be possible to pass internal investigation for both `master` and official rubocop (like now that CyclomaticComplexity has been tweaked), so run internal investigation only on `master`.
=> Run internal investigation using master only. Fix disabling

CHANGELOG.md, lib/rubocop/ast/node/regexp_node.rb, spec/rubocop/ast/regexp_node_spec.rb
As suggested by @bbatsov here:
https://github.com/rubocop-hq/rubocop/pull/8138#discussion_r439268175
=> Add `delimiters' and related predicates for `RegexpNode`

CHANGELOG.md, docs/modules/ROOT/pages/node_pattern.adoc, lib/rubocop/ast/node_pattern.rb, spec/rubocop/ast/node_pattern_spec.rb
This PR allows use of constants in a `NodePattern`, and allows keyword parameters (in addition to the existing sequential parameters).
Example [from the main gem](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/useless_comparison.rb#L15-L18)
```ruby
-       OPS = %w[== === != < > <= >= <=>].freeze
+       OPS = %i[== === != < > <= >= <=>].to_set.freeze
def_node_matcher :useless_comparison?,
-                        "(send $_match {:#{OPS.join(' :')}} $_match)"
+                        "(send $_match %OPS $_match)"
```
This would also be faster (doing a single hash lookup instead of 8 comparisons, see #29)
The keyword parameters is for cases where positional parameters wouldn't be as clear, but also because I would like to make it possible to specify some keyword …
=> NodePattern: Add Constants and keyword parameters

CHANGELOG.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/for_node_spec.rb, spec/rubocop/ast/send_node_spec.rb, spec/rubocop/ast/until_node_spec.rb, spec/rubocop/ast/while_node_spec.rb
https://github.com/rubocop-hq/rubocop-performance/pull/140/files#r439819074
There is already a second usage of such constants in the main repository:
https://github.com/rubocop-hq/rubocop/blob/eb3d358363a9f88a6ec2be485414f74b5f1b8878/lib/rubocop/cop/variable_force.rb#L46-L47
=> Add `post_condition_loop?` and `loop_keyword?` for `Node`

docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/node_types.adoc
Add documentation for node types and their corresponding classes in the code base.
I did run out of steam near the end and didn't document some of the more obscure nodes or the new pattern matching stuff. Let me know if this seems like it'd be useful - I spent quite a while figuring out a good way to present the information.
Going through this it also seems like there are many node classes that could use additional methods to make it easier to get the correct child nodes without having to mess with the index of the node in the child array. But that can come later.
=> [Fix #17] Add root documentation on what the gem does.

CHANGELOG.md, lib/rubocop/ast/traversal.rb
This PR Support find pattern matching for Ruby 2.8 (3.0) parser.
Parser gem supports this syntax by https://github.com/whitequark/parser/pull/714.
=> Support find pattern for pattern matching syntax

lib/rubocop/ast/node/array_node.rb, lib/rubocop/ast/node/case_match_node.rb, lib/rubocop/ast/node/case_node.rb, lib/rubocop/ast/node/if_node.rb, lib/rubocop/ast/node/when_node.rb, lib/rubocop/ast/processed_source.rb
These enumerating methods have only disadvantages compared to
the equivalent `conditions.each` / `values.each`. Mainly they are
less clear to a reader not familiar with them (higher cognitive load)
and offer no benefit (and are always less efficient)
Some also don't return an enumerator if called without a block.
Methods `find_...` feel even weaker; will we introduce `any_...`, `all_...`, `map_...`, etc? This is an anti-pattern.
Deprecation is documentation only; I don't feel it's worth actually warning / eventually removing them.
=> Deprecate all `each_...` and `find_...` that add no value

lib/rubocop/ast/node_pattern.rb, spec/rubocop/ast/hash_node_spec.rb, spec/rubocop/ast/node_pattern_spec.rb
Stricter handling of commas: leading or doubled commas are not accepted anymore
=> Node pattern refactoring

CHANGELOG.md, lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb
`ProcessedSource#commented?` was only considering the beginning line of the given range
=> Fix `ProcessedSource#commented?` for multi-line ranges. Add `ProcessedSource#commented_line?`

lib/rubocop/ast/node_pattern.rb
This reduces memory allocation from 19MB to 1.9MB (when run on cop/mixin).
Main issue remains that it is called way too many times though
=> Simplify and optimize.

.github/workflows/rubocop.yml
This way it's very clear if a PR fails because of the content of the code, or its styling.
=> CI: Split internal_investigation as its own CI job

CHANGELOG.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
=> Add struct_constructor?, class_definition? and module_definition? matchers

lib/rubocop/ast/processed_source.rb
In some circumstances, `ast` could be `false` instead of `nil`, `comments` and `tokens` could be `nil` instead of `[]`.
=> Fix `ProcessedSource` for cases with syntax errors

lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb
Insure correct values for `ast`, `comments` and `tokens`
Followup to #75
=> Fix `ProcessedSource` for cases with encoding errors.

CHANGELOG.md, lib/rubocop/ast/node/case_match_node.rb, lib/rubocop/ast/node/case_node.rb, lib/rubocop/ast/node/hash_node.rb, lib/rubocop/ast/node/if_node.rb, lib/rubocop/ast/node/pair_node.rb, lib/rubocop/ast/node/when_node.rb, lib/rubocop/ast/node_pattern.rb, lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/node_pattern_spec.rb, spec/rubocop/ast/node_spec.rb, spec/spec_helper.rb
=> `PairNode#delimiter` and `inverse_delimiter` now accept their argument as a named argument.

CHANGELOG.md, lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb
This PR:
* Adds `ProcessedSource#comment_at_line`
* Adds `ProcessedSource#each_comment_in_lines`
It deprecates `ProcessedSource#comments_before_line` (which is imo a big code smell).
I can't believe how much time I spent to arrive to this quite small PR; it's like version 5.0, I was really slow to get to this API.
I have reviewed / fixed all uses of any comment-accessing method in the main gem. The PR is upcomming. My main take is that any PR that autocorrects any range that could span more than one line must have specs with comments *on each single line* (close to that range).
=> Review comments API

CHANGELOG.md, lib/rubocop/ast.rb, lib/rubocop/ast/ext/range.rb, spec/rubocop/ast/ext/range_spec.rb
I've seen about 20 occurrences of `range.{first}line..{.}range.last_line` or calls to `line_range(node)` (defined in `util.rb`)
I feel the name `line_span` is more descriptive and is less confusing with `Source::Buffer#line_range` which returns a range of columns for the given line.
I notice that there currently are no extension to `parser`'s classes, but this one seems reasonable.
The result can be particularly useful when dealing with comments, say with `each_comment_in_lines` of #83
=> Add `Parser::Source::Range#line_span`

CHANGELOG.md, lib/rubocop/ast/node/case_node.rb, lib/rubocop/ast/node/if_node.rb, spec/rubocop/ast/case_node_spec.rb
I was surprised that `IfNode#branches` returns a array with a single item for `if foo; else; end`. I was expecting `[nil, nil]`, not just `[nil]`.
I mimicked this behavior for `CaseNode` as it seems natural to have this symmetry, but I wonder which is best. Anyone has an idea? cc/ @fatkodima
=> Add `CaseNode#branches`

CHANGELOG.md, lib/rubocop/ast/node.rb, lib/rubocop/ast/traversal.rb
This PR supports right hand assignment for Ruby 2.8.0-dev (Ruby 3.0).
https://github.com/whitequark/parser/pull/682
`mrasgn` has the same structure as `masgn` except that the child nodes are reversed. So this PR adds `mrasgn` to the same constant as `masgn`.
```console
% ruby-parse -e '13.divmod(5) => a, b'
warning: parser/current is loading parser/ruby28, which recognizes
warning: 2.8.0-dev-compliant syntax, but you are running 2.8.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(mrasgn
(send
(int 13) :divmod
(int 5))
(mlhs
(lvasgn :a)
(lvasgn :b)))
```
```console
% ruby-parse -e 'a, b = 13.divmod(5)'
warning: parser/current is loading parser/ruby28, which recognizes
warning: 2.8.0-dev-compliant syntax, but you are running 2.8.0.
warning: please …
```
=> Support right hand assignment

CHANGELOG.md
I wrote #89's changelog entry in the released section by mistake 💦  This PR tweaks the changelog entry.
=> Tweak the changelog

CHANGELOG.md, lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb
Context - https://github.com/rubocop-hq/rubocop/pull/8450
That was merged a bit fast 😄  - will send PR with refactorings when this will be released.
=> Add `ProcessedSource#tokens_within`, `ProcessedSource#first_token_of` and `ProcessedSource#last_token_of`

CHANGELOG.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
[Requested](https://github.com/rubocop-hq/rubocop/pull/8474#discussion_r466959357) by @fatkodima
=> Add Node#left_sibling, right_sibling, left_siblings and right_siblings

Gemfile
Otherwise, it's impossible to run `rubocop` locally.
For frequent contributors those gems are already packed in `Gemfile.local`, but for first-time contributors it's not the case.
=> Add RuboCop and extensions for local dev

docs/modules/ROOT/pages/node_pattern.adoc, lib/rubocop/ast/node_pattern.rb
Should be `def_node_matcher`, not `def_node_pattern`. At least, I couldn't find the latter being defined anywhere.
=> Fix typo in node pattern defining method name

CHANGELOG.md, lib/rubocop/ast.rb, lib/rubocop/ast/ext/set.rb, spec/rubocop/ast/ext/set_spec.rb
This makes it possible to use `Set` in `NodePattern` on all supported Ruby versions.
cc @bbatsov
=> In Ruby 2.4, `Set#===` is harmonized with Ruby 2.5+ to call `include?`

CHANGELOG.md, lib/rubocop/ast/node/const_node.rb, spec/rubocop/ast/const_node_spec.rb
Came up in https://github.com/rubocop-hq/rubocop/pull/8738.
When there is no namespace, `each_path.first` is nil, which caused
```
NoMethodError: undefined method `cbase_type?' for nil:NilClass
```
=> Fix `ConstNode#absolute?` raising `NoMethodError` when the constant is not namespaced

lib/rubocop/ast/processed_source.rb
For context - https://github.com/rubocop-hq/rubocop/pull/8729
=> Use stable sort when sorting tokens

spec/rubocop/ast/send_node_spec.rb, spec/spec_helper.rb
Many tests in `rubocop-ast` need to generate an AST from Ruby code and then select an inner node.
It is very difficult to tell when reading the test which node it is:
```ruby
let(:send_node) { parse_source(source).ast.children[2].children[0] }
let(:source) do
['class Foo',
'  bar :baz',
'  bar :qux',
'end'].join("\n")
end
```
With this PR, we can target a particular node by wrapping it between `'>>'` and `'<<'` and `parse_source` can then target it by matching the source:
```ruby
let(:source) do
['class Foo',
'>>bar :baz<<',
'  bar :qux',
'end'].join("\n")
end
```
=> `parse_source`: allow direct targetting of a node

CHANGELOG.md, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec
Parser 2.7.1.5 includes https://github.com/whitequark/parser/pull/729 and this PR updates from `Parser::Ruby28` to `Parser::Ruby30` for Ruby 3.0 parser.
=> Update from `Parser::Ruby28` to `Parser::Ruby30` for Ruby 3.0 parser

.github/workflows/rubocop.yml, CHANGELOG.md, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, lib/rubocop/ast/rubocop_compatibility.rb, spec/rubocop/ast/rubocop_compatibility_spec.rb, spec/rubocop/ast/send_node_spec.rb
This PR fixes rubocop-hq/rubocop#8765
There were many issues with how `macro_scope?`:
* recursion was badly written, so many cases were not handled well
* `if` did not distinguish if in the conditions part or on of the bodies
It also introduces `Node#parent?`
Builds on #119 
I'll do a final review when I'm less sleepy 😅
=> Fix macro?

CHANGELOG.md, lib/rubocop/ast/node/regexp_node.rb, spec/rubocop/ast/regexp_node_spec.rb
I'll need this for https://github.com/rubocop-hq/rubocop/pull/8625 to pass the options through to `regexp_parser`
=> Add `RegexpNode#options`

lib/rubocop/ast/node_pattern/lexer.rb, rubocop-ast.gemspec
Restores [compatibility with JRuby](https://github.com/jruby/jruby/issues/6414)
=> Avoid using `StringScanner#captures`, any `strscan` lib will do

CONTRIBUTING.md, changelog/new_add_rake_tasks_to_merge_and_create.md, spec/tasks/changelog_spec.rb, tasks/changelog.rake, tasks/changelog.rb, tasks/cut_release.rake
Fixes rubocop-hq/rubocop#8697
After yet another Changelog merge issue, I decided to write some code to avoid it.
This PR adds a rake task to merge entries in `CHANGELOG/` according to the prefix of their path: "new" (feature), (bug) "fix" or "change". It merges those with any existing entries in the unreleased section of the Changelog, so it can be done at any moment, is backward compatible, and nobody is forced to use it (except before cutting a release, and I've added a check for that 😅).
Other rake task `cl:new`, `cl:fix`, `cl:change` create an entry file (default use the last commit's message & git config).
For a contributor, the workflow looks like this:
* make a contribution, test it, etc.
* `git commit` (enter a good commit message, optionally starting with `[Fixes #xxx]`)
* …
=> Add rake tasks to merge and create Changelog entries

CHANGELOG.md, changelog/fix_only_traverse_send_nodes_in_def_modifier.md, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, spec/rubocop/ast/send_node_spec.rb
A send node is a "def modifier" if it's part of a chain of method calls preceding a method definition. However the previous implementation was too permissive and matched any method definition in the send node's AST.
In the following example, `include` was considered to be a def modifier:
```ruby
include Module.new {
private def foo
end
}
```
This is the root cause of the problem fixed in https://github.com/rubocop-hq/rubocop/pull/8653.
=> Only traverse send nodes in def_modifier?

docs/modules/ROOT/pages/node_pattern_compiler.adoc, lib/rubocop/ast/node_pattern.rb, lib/rubocop/ast/node_pattern/builder.rb, lib/rubocop/ast/node_pattern/compiler.rb, lib/rubocop/ast/node_pattern/compiler/atom_subcompiler.rb, lib/rubocop/ast/node_pattern/compiler/node_pattern_subcompiler.rb, lib/rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb, lib/rubocop/ast/node_pattern/compiler/subcompiler.rb, lib/rubocop/ast/node_pattern/lexer.rb, lib/rubocop/ast/node_pattern/parser.rb
Follow https://github.com/rubocop-hq/rubocop-ast/commit/2ca9c08b
This PR fixes node_pattern documentation path and recovers dead link on the following document page.
https://docs.rubocop.org/rubocop-ast/1.0/node_pattern_compiler.html
=> Fix node_pattern documentation path

CHANGELOG.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/send_node_spec.rb
This PR makes `SendNode#macro?` aware of struct constructor.
Like class constructor, struct constructor will be recognized as a macro and will be awakened in the following `private` modifier:
```ruby
Foo = Struct.new(:foo) do
private
def private_foo
foo
end
end
```
With this change, this PR aims to resolve the following issue.
https://github.com/rubocop-hq/rubocop/issues/8919
=> Make `SendNode#macro?` aware of struct constructor

CHANGELOG.md, lib/rubocop/ast/node/if_node.rb, spec/rubocop/ast/if_node_spec.rb
Currently, it is returning only 1 branch.
=> Fix `IfNode#branches` to return both branches when called on ternary conditional

.rubocop.yml
This single cop generates 372 offenses, e.g. "Example group has too many memoized helpers [19/5]"
https://github.com/rubocop-hq/rubocop-rspec/pull/863
=> Disable `RSpec/MultipleMemoizedHelpers`

changelog/change_def_node_pattern_and_def_node_search_now.md, lib/rubocop/ast/node_pattern/method_definer.rb, spec/rubocop/ast/node_pattern_spec.rb
See https://github.com/rubocop-hq/rubocop/pull/7695
=> `def_node_pattern` and `def_node_search` now return the method name.

.github/workflows/rubocop.yml, docs/modules/ROOT/pages/node_types.adoc, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/regexp_node.rb, lib/rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb, lib/rubocop/ast/node_pattern/node.rb, rubocop-ast.gemspec, spec/rubocop/ast/if_node_spec.rb, spec/rubocop/ast/lambda_node_spec.rb
See https://github.com/whitequark/parser/pull/739
=> Remove `:rasgn` and `:mrasgn` types.

lib/rubocop/ast.rb, lib/rubocop/ast/ext/range_min_max.rb, lib/rubocop/ast/node_pattern/node.rb
Cleans up the code and cleaner detection.
See [this discussion](https://github.com/rubocop-hq/rubocop-ast/pull/150#issuecomment-726865019)
=> Use refinements to support Ruby <= 2.6 Range#minmax

.github/workflows/rubocop.yml, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/array_node.rb, lib/rubocop/ast/node/case_match_node.rb, lib/rubocop/ast/node/case_node.rb, lib/rubocop/ast/node/const_node.rb, lib/rubocop/ast/node/hash_node.rb, lib/rubocop/ast/node/if_node.rb, lib/rubocop/ast/node/mixin/descendence.rb, lib/rubocop/ast/node/when_node.rb, lib/rubocop/ast/node_pattern.rb, lib/rubocop/ast/node_pattern/lexer.rb
This PR fixes the following GitHub Actions error.
```console
Run echo '::set-env name=RUBOCOP_VERSION::master'
Error: Unable to process command '::set-env
name=RUBOCOP_VERSION::master' successfully.
Error: The `set-env` command is disabled. Please upgrade to using
Environment Files or opt into unsecure command execution by setting the
`ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For
more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
https://github.com/rubocop-hq/rubocop-ast/pull/152/checks?check_run_id=1438579176
=> Fix deprecating `set-env` for GitHub Actions

changelog/change_enable_blocknodeargument_list_for.md, lib/rubocop/ast/node/block_node.rb, spec/rubocop/ast/block_node_spec.rb
Follows #154 (I'll rebase away that commit once merged).
`numblock`s now return an array of `ArgNode`s from `BlockNode#argument_list`, ~and `BlockNode#arguments?` is true for `numblock`s.~
=> Enable `BlockNode#argument_list` for `numblock`s. 

changelog/fix_nodepattern_now_considers_constant_names.md, docs/modules/ROOT/pages/node_pattern.adoc, lib/rubocop/ast/node_pattern/lexer.rex, spec/rubocop/ast/block_node_spec.rb, spec/rubocop/ast/node_pattern/lexer_spec.rb
(instead of predicate `#Example_type?`)
[Fixes #156]
=> NodePattern now considers constant names to refer to constants

README.md, lib/rubocop/ast/builder.rb, lib/rubocop/ast/traversal.rb, spec/spec_helper.rb
This flag improves the API for Ruby 3.0; I don't think any cop was relying on pattern match `in` operator in Ruby 2.7 (was officially experimental)
=> Turn on 'emit_match_pattern'

docs/modules/ROOT/pages/node_pattern.adoc
I was looking at the docs today and noticed that the section for arguments defines a node matcher as `has_sensitive_data?`, however it then goes on to use `has_user_data?` in examples.
=> Replace incorrect node_matcher name

lib/rubocop/ast/node_pattern.rb
Now when this line is joined with the next line (as it will be on
[rubydoc.info](https://www.rubydoc.info/gems/rubocop-ast/RuboCop/AST/NodePattern/Macros#def_node_matcher-instance_method)), it won't turn into a run-on sentence.
See:
=> Add a period to the end of a sentence in the documentation

.rubocop.yml, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, lib/rubocop/ast/node/send_node.rb
Adds `@!method` directives to node matcher definitions, as per rubocop/rubocop#9506.
=> Add annotations for pattern matcher definitions

changelog/new_support_ruby_3_1_parser.md, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec, spec/spec_helper.rb
Parser gem has been started development for Ruby 3.1 (edge Ruby).
https://github.com/whitequark/parser/pull/792
This PR supports `Parser::Ruby31`, the early adapters will be able to try edge Ruby with RuboCop.
And this PR update to require Parser 3.0.1.1 or higher, which contains `Parser::Ruby31`.
https://github.com/whitequark/parser/blob/master/CHANGELOG.md#v3011-2021-05-02
=> Support `Parser::Ruby31`

docs/modules/ROOT/pages/node_types.adoc
After the namespace upgrade from "rubocop-hq" to "rubocop", the links to rubydoc are broken as rubydoc dose not offer redirection.
I didn't rename github urls since they work currently.
=> Fix doc url to Rubydoc

changelog/new_add_pattern_method_for_ast_in_pattern_node, lib/rubocop/ast/node/in_pattern_node.rb, spec/rubocop/ast/in_pattern_node_spec.rb
This PR adds `pattern` method for `AST::InPatternNode`.
=> Add `pattern` method for `AST::InPatternNode`

docs/modules/ROOT/pages/node_pattern.adoc
=> Fix an adoc syntax typo in Node Pattern docs

changelog/change_escape_references_in_docs.md, docs/modules/ROOT/pages/node_types.adoc
When generating documentation `{bar}` in the documentation triggers a warning like:
```
asciidoctor: WARNING: skipping reference to missing attribute: bar
```
This is part of the the reason for [this issue](https://github.com/rubocop/rubocop/issues/9150) in the Rubocop repository (although there are other places that this can be seen in other Rubocop repositories).
To test:
```shell
rubocop-ast git:(wm/escape_references_in_docs) > git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
rubocop-ast git:(master) > asciidoctor -a attribute-missing=warn docs/modules/ROOT/pages/node_types.adoc -o master.html
asciidoctor: WARNING: skipping reference to missing attribute: bar
asciidoctor: WARNING: skipping reference to missing attribute: bar
asciidoctor: …
```
=> Escape special chars in docs

lib/rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb, lib/rubocop/ast/node_pattern/parser.rb, spec/rubocop/ast/node_pattern_spec.rb
This PR suppresses and auto-corrects the following RuboCop 1.8's new offense.
```console
% bundle exec rubocop -a
(snip)
Inspecting 3 files
CCC
Offenses:
lib/rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb:350:13: C:
[Corrected] Layout/LineEndStringConcatenationIndentation: Indent the first part of a string concatenated with backslash.
"#{@cur_child_var} || true)"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/ast/node_pattern/parser.rb:55:13: C: [Corrected]
Layout/LineEndStringConcatenationIndentation: Align parts of a string concatenated with backslash.
"but got expression matching multiple elements: #{detail}"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/rubocop/ast/node_pattern_spec.rb:948:9: C: [Corrected]
Layout/LineEndStringConcatenationIndentation: Indent …
```
=> Suppress RuboCop 1.8's new offense

changelog/add_branches_method_for_ast_case_match_node.md, lib/rubocop/ast/node/case_match_node.rb, spec/rubocop/ast/case_match_node_spec.rb
This PR adds `branches` method for `AST::CaseMatchNode`.
This makes a method similar to `AST::CaseNode#branches` available in `AST::CaseMatchNode`.
After this, I will be developing with this API on RuboCop.
=> Add `branches` method for `AST::CaseMatchNode`

lib/rubocop/ast/node/case_match_node.rb, spec/rubocop/ast/case_match_node_spec.rb, spec/rubocop/ast/case_node_spec.rb
Follow https://github.com/whitequark/parser/pull/652.
This PR adds doc and spec for `empty-else` node.
Below is a description of `empty-else` node.
> Empty `else` differs from the missing (or _implicit_) `else` for pattern
> matching, since
> the latter one raises a `NoMatchingPattern` exception. Thus, we need a
> way to distinguish this two cases in the resulting AST.
https://github.com/whitequark/parser/blob/v3.0.1.1/doc/AST_FORMAT.md#with-empty-else
Below are the differences between each AST (`empty-else` only appears in the last case).
```console
% ruby-parse -e 'case foo; when bar; end'
(case
(send nil :foo)
(when
(send nil :bar) nil) nil)
% ruby-parse -e 'case foo; when bar; else; end'
(case
(send nil :foo)
(when
(send nil :bar) nil) nil)
% ruby-parse -e 'case foo; in bar; end' …
```
=> Add doc and spec for `empty-else` node

.rubocop.yml, lib/rubocop/ast/node_pattern.rb
`Layout/LeadingCommentSpace` was updated in rubocop/rubocop#9964 to consider `:nodoc:`
=> Fix `Layout/LeadingCommentSpace` offenses

lib/rubocop/ast/processed_source.rb
A number of cops are not detecting issues when looking at tokens around heredocs (for instance `Layout/SpaceInsideParams`) because they use pairs of tokens, but the tokens are not sorted properly for heredocs as method arguments (as per the comment of `ProcessedSource#sorted_tokens`).
For instance, this space is not detected by `Layout/SpaceInsideParams` currently because the tokens are not sorted in the expected order:
```ruby
foo(<<~STR )
text
STR
```
This change just moves that method to be public so that the cops can use it.
=> Move `ProcessedSource#sorted_tokens` to be a public method

changelog/fix_fix_184_fix_nodeparent_module_name_for.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
Continuation of #177. I took @marcandre's tests and got them to pass. This fixes rubocop/rubocop#5022, but rubocop itself needs a PR as well because this change adds elements to the `parent_module_name` that it is not currently expecting.
=> [Fix #184] Fix `Node#parent_module_name` for `sclass` nodes

lib/rubocop/ast/node_pattern/node.rb
This PR fixes a tiny typo. 🧑‍🔧
=> node.rb: fix typo in comment

lib/rubocop/ast/node/const_node.rb
Looks like `ConstNode` was copied from `BlockNode` and left some unrelated comments.
=> Remove unrelated comments from `ConstNode`

changelog/new_make_class_module_struct_definition_aware_of_numblock.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
This PR makes class, module, and struct definitions aware of numblock.
=> Make class, module, and struct definitions aware of numblock

lib/rubocop/ast/node.rb, spec/rubocop/ast/node_pattern/lexer_spec.rb
This PR suppresses the following `Lint/AmbiguousOperatorPrecedence` offense.
```console
% bundle exec rake
(snip)
Offenses:
lib/rubocop/ast/node.rb:428:44: W: [Correctable]
Lint/AmbiguousOperatorPrecedence: Wrap expressions with varying
precedence with parentheses to avoid ambiguity.
return true if special_keyword? || send_type? && prefix_not?
^^^^^^^^^^^^^^^^^^^^^^^^^
spec/rubocop/ast/node_pattern/lexer_spec.rb:70:27: W: [Correctable]
Lint/AmbiguousOperatorPrecedence: Wrap expressions with varying
precedence with parentheses to avoid ambiguity.
expect(types).to eq [:tNODE_TYPE] * 2 + [:tPARAM_CONST] * 7
^^^^^^^^^^^^^^^^^
spec/rubocop/ast/node_pattern/lexer_spec.rb:70:47: W: [Correctable]
Lint/AmbiguousOperatorPrecedence: Wrap expressions with varying
precedence with parentheses to avoid …
```
=> Suppress `Lint/AmbiguousOperatorPrecedence` offense

CHANGELOG.md, CONTRIBUTING.md, Gemfile, README.md, docs/modules/ROOT/pages/node_pattern.adoc, docs/modules/ROOT/pages/node_pattern_compiler.adoc, rubocop-ast.gemspec, spec/rubocop/ast/send_node_spec.rb, spec/tasks/changelog_spec.rb, tasks/changelog.rb
Follow up to https://github.com/rubocop/rubocop/pull/9537.
=> Update `rubocop-hq` org to `rubocop` org

changelog/fix_fix_208_update.md, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, spec/rubocop/ast/send_node_spec.rb
If a send node has a numblock as a parent, `block_literal?` returns false, but this changes it to treat `numblock`s the same as regular `block`s. This also makes `send_node.block_node` return a `numblock` if applicable.
Fixes #208.
=> [Fix #208] Update `MethodDispatchNode#block_literal?` to return true for `numblock`s

changelog/new_make_numeric_type_predicate_aware_of_rational_and_complex.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
This PR makes `Node#numeric_type?` aware of complex and rational literals.
These literals could be treated as numeric.
```ruby
42r.is_a?(Numeric)  # => true
42i.is_a?(Numeric)  # => true
42ri.is_a?(Numeric) # => true
```
=> Make `Node#numeric_type?` aware of rational and complex literals

rubocop-ast.gemspec
Follows rubocop/rubocop#10239. Update gemspec to require MFA for privileged operations.
=> Set `rubygems_mfa_required` in gemspec

changelog/new_support_ruby31_anonymous_block_forwarding_syntax.md, lib/rubocop/ast/traversal.rb, spec/rubocop/ast/traversal_spec.rb
Follow up to https://github.com/whitequark/parser/pull/833.
Here is a traditional block forwarding.
```console
% ruby-parse -e 'def foo(&b) = bar(&b)'
warning: parser/current is loading parser/ruby31, which recognizes
warning: 3.1.0-dev-compliant syntax, but you are running 3.1.0.
warning: please see
https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(def :foo
(args
(blockarg :b))
(send nil :bar
(block-pass
(lvar :b))))
```
The anonymous block forwarding introduced in Ruby 3.1, the value of `block-pass` is nil.
So `block-pass` will have the possibility of having nil.
```console
% ruby-parse -e 'def foo(&) = bar(&)'
warning: parser/current is loading parser/ruby31, which recognizes
warning: 3.1.0-dev-compliant syntax, but you are running 3.1.0.
warning: please see …
```
=> Support Ruby 3.1's anonymous block forwarding syntax

changelog/new_add_value_omission_to_pair_node.md, lib/rubocop/ast/node/pair_node.rb, spec/rubocop/ast/pair_node_spec.rb
Follow up to https://github.com/whitequark/parser/pull/818
This PR adds `value_omission` method to `AST::PairNode` for Ruby 3.1's hash value omission.
It can replace string match with that named API.
=> Add `value_omission` method to `AST::PairNode`

changelog/fix_make_node_receiver_aware_of_csend.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/block_node_spec.rb
Resolves: https://github.com/rubocop/rubocop/issues/10319.
This PR makes the following behavior of `send` calls and `csend` calls consistent.
Before:
- The receiver of `foo.bar { baz }` is `foo`.
- The receiver of `foo&.bar { baz }` is `nil`.
After:
- The receiver of `foo.bar { baz }` is `foo`.
- The receiver of `foo&.bar { baz }` is `foo`.
=> Make `AST::Node#receiver` aware of `csend` block method calls

changelog/new_support_ruby_3_2_parser.md, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec, spec/spec_helper.rb
Parser gem has been started development for Ruby 3.2 (edge Ruby).
https://github.com/whitequark/parser/pull/841
This PR supports `Parser::Ruby32`, the early adapters will be able to try edge Ruby with RuboCop.
And this PR update to require Parser 3.1.1.0 or higher, which contains `Parser::Ruby32`.
https://github.com/whitequark/parser/blob/master/CHANGELOG.md#v3110-2022-02-21
=> Support `Parser::Ruby32`

changelog/new_make_node_condition_p_aware_of_case_match.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
This PR makes `Node#condition?` aware of `case-match` node.
=> Make `Node#condition?` aware of `case-match` node

Gemfile, lib/rubocop/ast/traversal.rb
This PR suppresses the following RuboCop offenses.
```console
% bundle exec rake
(snip)
Offenses:
Gemfile:21:4: C: [Correctable] Style/FetchEnvVar:
Use ENV.fetch('RUBOCOP_VERSION') or ENV.fetch('RUBOCOP_VERSION', nil) instead of ENV['RUBOCOP_VERSION'].
if ENV['RUBOCOP_VERSION'] == 'none'
^^^^^^^^^^^^^^^^^^^^^^
Gemfile:28:9: C: [Correctable] Style/FetchEnvVar:
Use ENV.fetch('RUBOCOP_VERSION') or ENV.fetch('RUBOCOP_VERSION', nil) instead of ENV['RUBOCOP_VERSION'].
elsif ENV['RUBOCOP_VERSION'] == 'master'
^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/ast/traversal.rb:37:39: C: [Correctable] Style/FetchEnvVar:
Use ENV.fetch('RUBOCOP_DEBUG') or ENV.fetch('RUBOCOP_DEBUG', nil) instead of ENV['RUBOCOP_DEBUG'].
arity_check: ENV['RUBOCOP_DEBUG'] && self.arity_check(arity),
^^^^^^^^^^^^^^^^^^^^
162 files …
```
=> Suppress RuboCop offenses

.github/workflows/rubocop.yml, .rubocop.yml, changelog/change_drop_ruby_25.md, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/mixin/parameterized_node.rb, lib/rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb, lib/rubocop/ast/node_pattern/node.rb, lib/rubocop/ast/traversal.rb, rubocop-ast.gemspec
Follow up https://github.com/rubocop/rubocop/pull/10577.
=> Drop Ruby 2.5 support

changelog/new_make_parse_from_ruby_19_to_23_available.md, lib/rubocop/ast/processed_source.rb
RuboCop can analyze Ruby 1.9 or later. But now it turns out that RuboCop hasn't been able to parse older Ruby versions.
https://docs.rubocop.org/rubocop/1.29/compatibility.html#support-matrix
Analysis Ruby code and runtime Ruby versions are different. So, only runtime version should have been dropped.
This PR makes it possible to parse older Ruby versions that were accidentally dropped before RuboCop AST was separated from RuboCop core.
With this fix, the following recovery work will be possible.
- Recover for Ruby 2.5 analysis: https://github.com/rubocop/rubocop/pull/10626
- Recover for Ruby 2.4 analysis: https://github.com/rubocop/rubocop/pull/10632
=> Make parse from Ruby 1.9 to 2.3 available

changelog/new_add_regexp_dot_p_to_token.md, lib/rubocop/ast/token.rb, spec/rubocop/ast/token_spec.rb
Follow up #https://github.com/rubocop/rubocop/pull/10798.
This PR adds `ragexp_dot?` method to `RuboCop::AST::Token`.
=> Add `ragexp_dot?` method to `RuboCop::AST::Token`.

changelog/change_rename_regexp_dot_to_regexp_dots.md, lib/rubocop/ast/token.rb, spec/rubocop/ast/token_spec.rb
Follow up https://github.com/rubocop/rubocop-ast/pull/235#issuecomment-1179649807.
This PR renames `RuboCop::AST::Token#regexp_dot?` to `RuboCop::AST::Token#regexp_dots`.
It's been determined that it doesn't need to be an alias because it's the API that has just been released and isn't widespread.
=> Rename `RuboCop::AST::Token#regexp_dot?` to `RuboCop::AST::Token#regexp_dots`

changelog/fix_regexp_node_aware_of_fixed_encoding_regopt.md, lib/rubocop/ast/node/regexp_node.rb, spec/rubocop/ast/regexp_node_spec.rb
Resolves https://github.com/rubocop/rubocop/issues/10552.
This PR makes `RegexpNode` aware of fixed-encoding regopt.
=> Make `RegexpNode` aware of fixed-encoding regopt

changelog/new_fix_macro_for_numblock_nodes.md, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, spec/rubocop/ast/send_node_spec.rb
We can have macros in numblocks. I found this issue while working on broader `numblock` nodes support for cops in rubocop and found out that the`#bare_access_modifier?` method was not giving proper results for modifiers in numblocks. This applies to other methods that depend on the `#macro?` method.
=> Fix #macro? for numblock nodes

changelog/new_add_a_type_predicate_dot_to_token.md, lib/rubocop/ast/token.rb, spec/rubocop/ast/token_spec.rb
When I was working on fixing Cop related to dot position in rubocop/rubocop, I thought it would be nice to have `dot?` in the Token.
I ended up taking a different approach at the time, but I'm sending a PR because I think it may be used in the future.
=> Add a type predicate `dot?` to Token

.github/workflows/rubocop.yml
* See https://github.com/oracle/truffleruby/issues/2290
=> Use TRUFFLERUBYOPT=--engine.Mode=latency to speed up CI on TruffleRuby

changelog/new_add_character_literal_to_str_node.md, lib/rubocop/ast/node/str_node.rb, spec/rubocop/ast/str_node_spec.rb
This PR adds `character_literal?` to `StrNode`.
`...begin.is?('?')` used in https://github.com/rubocop/rubocop/pull/11095 and `Style/CharacterLiteral` can be rewritten by `node.character_literal?`.
=> Add `character_literal?` to `StrNode`

spec/rubocop/ast/node_pattern/lexer_spec.rb
This PR is fixed several offenses of `RSpec/ExampleWording`.
```ruby
❯ bundle exec rubocop
Inspecting 162 files
.............................................................................................................................C....................................
Offenses:
spec/rubocop/ast/node_pattern/lexer_spec.rb:34:9: C: RSpec/ExampleWording: Your example description is insufficient.
it 'works' do
^^^^^
spec/rubocop/ast/node_pattern/lexer_spec.rb:80:9: C: RSpec/ExampleWording: Your example description is insufficient.
it 'works' do
^^^^^
162 files inspected, 2 offenses detected
```
=> Fix some offenses for `RSpec/ExampleWording`

changelog/new_add_node_types_forwarded_restarg_and_forwarded_kwrestarg.md, docs/modules/ROOT/pages/node_types.adoc, lib/rubocop/ast/traversal.rb
This PR is added the node types added by https://github.com/whitequark/parser/pull/874
Now CI seems to be failing as well: 
https://github.com/rubocop/rubocop-ast/actions/runs/3581987367/jobs/6025686164#step:9:33
=> Add node types `forwarded_restarg` and `forwarded_kwrestarg`

docs/modules/ROOT/pages/node_pattern_compiler.adoc
This fixes the formatting of the "visitor pattern" link:
<table><tr><th>Before</th><th>After</th></tr>
<tr><td><blockquote>...the visitor pattern [https://en.wikipedia.org/wiki/Visitor_pattern]</blockquote></td><td><blockquote>...the <a href="https://en.wikipedia.org/wiki/Visitor_pattern">visitor pattern</a></blockquote></td></tr></table>
[This page on ASCII Doc](https://docs.asciidoctor.org/asciidoc/latest/macros/url-macro/#link-text) explains how to format links correctly.
=> Fix visitor pattern link formatting

.github/workflows/rubocop.yml
This PR is add Ruby 3.2 to the CI matrix
Because Ruby 3.2.0 is now in general release, it makes sense to add Ruby 3.2 to the CI matrix.
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
=> Add Ruby 3.2 to the CI matrix

.github/workflows/rubocop.yml, .github/workflows/spell_checking.yml
Same as: https://github.com/rubocop/rubocop-rspec/pull/1539
This PR ensures that only the last execution per branch always works, even when pushed multiple times in a row, for example. The older one is canceled.
Refs:
https://docs.github.com/en/actions/using-jobs/using-concurrency https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
=> Use concurrency for GitHub Actions workflow

lib/rubocop/ast/node/csend_node.rb
This PR is use `csend` instead of `send` in CsendNode class documentation
=> Use `csend` instead of `send` in CsendNode class documentation

docs/modules/ROOT/pages/node_types.adoc
This PR is improve the code example about `xstr`.
The code example for `xstr` appears to be incorrect from the [documentation](https://docs.rubocop.org/rubocop-ast/node_types.html).
The `foo#bar` looks more incorrect because it also looks like `dstr` and the backtick is not escaped.
Therefore, we would like to suggest using  \`date\` as a code example, as used in the following https://docs.ruby-lang.org/ document.
https://docs.ruby-lang.org/en/master/Kernel.html#method-i-60:~:text=%24-,%60date%60,-%23%20%3D%3E%20%22Wed%20Apr%20%209
After:
=> Improve the code example about `xstr`

changelog/new_support_ruby_3_3_parser.md, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec, spec/spec_helper.rb
Parser gem has been started development for Ruby 3.3 (edge Ruby).
https://github.com/whitequark/parser/pull/904
And this PR update to require Parser 3.2.1.0 or higher, which contains `Parser::Ruby33`. https://github.com/whitequark/parser/blob/master/CHANGELOG.md#v3210-2023-02-09
=> Support `Parser::Ruby33`

changelog/new_make_class_constructor_aware_of_data_class.md, changelog/new_make_class_constructor_aware_of_numbered_parameters.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
This PR contains the following two commits:
Ruby 3.2 introduced immutable `Data.define`. Since this is similar to `Struct.new`, `Node#class_constructor` will handle it in the same way.
`Class.new`, `Module.new`, `Struct.new`, and `Data.define` take themselves as a block parameter.
These are the same when using numbered block parameter.
I will try to update https://github.com/rubocop/rubocop/pull/11546 and https://github.com/rubocop/rubocop/pull/11547 with this feature.
=> Make `Node#class_constructor?` aware of `Data.define` and numbered parameters

changelog/new_add_source_range_to_node_pattern.md, lib/rubocop/ast/ext/range.rb, lib/rubocop/ast/node_pattern/compiler/debug.rb, lib/rubocop/ast/node_pattern/node.rb, lib/rubocop/ast/node_pattern/with_meta.rb, spec/rubocop/ast/ext/range_spec.rb, spec/rubocop/ast/processed_source_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/11630.
This PR provides a shorthand for `source_range` to `NodePattern`, like `RuboCop::AST::Node#source_range`. It will make a consistent rewrite of `loc.expression` to `source_range`. And resolves the following errors.
```console
% bundle exec rake
(snip)
Failures:
1) RuboCop::AST::NodePattern::Parser sequences parses simple sequences properly
Failure/Error: expr = children.first.source_range.join(children.last.source_range)
NoMethodError: (-) undefined method `source_range' for s(:node_type, :int):RuboCop::AST::NodePattern::Node
```
=> Add `source_range` method to `NodePattern`

.github/workflows/rubocop.yml
The master brach of RuboCop has been dropped Ruby 2.6 runtime support. https://github.com/rubocop/rubocop/pull/11791
This PR fixes the following build error:
```
Run cd ../rubocop && bundle install --jobs 3 --retry 3
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler.
Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version.
Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Could not find compatible versions
Because every version of rubocop depends on Ruby >= 2.7.0
and Gemfile depends on rubocop >= 0,
Ruby >= 2.7.0 is required.
So, because …
```
=> Fix a build error when using Ruby 2.6 runtime

changelog/fix_an_error_when_parsing_non_utf_8_frozen_string.md, lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb
This PR fixes the following `FrozenError` when parsing non UTF-8 frozen string:
```console
$ cat example.rb
require 'rubocop-ast'
RuboCop::AST::ProcessedSource.new('true', 3.2)
```
```console
$ ruby example.rb
/Users/koic/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.28.0/lib/rubocop/ast/processed_source.rb:30:
in `force_encoding': can't modify frozen String: "true" (FrozenError)
from /Users/koic/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.28.0/lib/rubocop/ast/processed_source.rb:30:
in `initialize'
from example.rb:6:in `new'
from example.rb:6:in `<main>'
```
=> Fix an error when parsing non UTF-8 frozen string

Gemfile, rubocop-ast.gemspec
see https://github.com/rubocop/rubocop-ast/actions/runs/5039437879/jobs/9037577956
````
rubocop-ast.gemspec:38:3: C: Gemspec/DevelopmentDependencies: Specify development dependencies in Gemfile.
s.add_development_dependency('bundler', '>= 1.15.0', '< 3.0')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Fix new cop offense (for green ci)

docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/node_pattern.adoc
This:
- adds a smooth introduction to AST, basic node pattern usages
- adds a section for negation syntax
- small fixes
fixes #228
=> Improve docs

CHANGELOG.md, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, spec/rubocop/ast/super_node_spec.rb, spec/rubocop/ast/yield_node_spec.rb
If you need to manipulate the call-site of a method dispatch, you have to use `node.loc.selector` for regular methods and `node.loc.keyword` for syntax nodes that behave like method invocations. Super and yield nodes are nodes are examples.
This forces us to check if `node.loc` responds to `#keyword` in a few places in rubocop proper and we can make it easier if we expose a single method called `#selector` (the name is up for debate) and use it for method dispatch nodes.
As an example, see [HashSyntaxShorthand](https://github.com/rubocop/rubocop/blob/7259df96e689f80828eb231495cc515011585bd9/lib/rubocop/cop/mixin/hash_shorthand_syntax.rb#L206-L224) where I had to define a struct to hide away the selector detection.
=> Introduce RuboCop::Ast::MethodDispatchNode#selector

lib/rubocop/ast/node/if_node.rb
This just fixes a typo in a comment. For some reason it caused failing CI on #270.
=> Fix "Chacks" -> "Checks" typo

changelog/new_add_blocknodefirstlast_argument_helpers.md, lib/rubocop/ast/node/block_node.rb, lib/rubocop/ast/node/if_node.rb, spec/rubocop/ast/block_node_spec.rb
These methods allow more consistent use of `first_argument` and `last_argument` across more node types.
The motivation for this PR is to allow for an `InternalAffairs/NodeFirstArgument` cop to enforce `node.arguments.first` and `node.arguments[0]` be replaced with `node.first_argument`. For this to be possible, we need to extend `first_argument` to other node types, since the cop can't statically know what the node type is to determine if the method exists or not.
=> Add `BlockNode#{first,last}_argument` helpers

docs/modules/ROOT/pages/node_types.adoc
* Changes some types from being dash-delimited to using underscores. The dash variants don't seem to actually exist.
* Changes one ruby version reference from 2.8 to 3.0
=> Fix a few small things in NodeTypes docs

changelog/new_support_ruby_3_4_parser.md, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec, spec/spec_helper.rb
Parser gem has been started development for Ruby 3.4 (edge Ruby).
https://github.com/whitequark/parser/pull/991
And this PR update to require Parser 3.3.0.4 or higher, which contains `Parser::Ruby34`. https://github.com/whitequark/parser/blob/master/CHANGELOG.md#not-released-2024-01-15
=> Support `Parser::Ruby34`

spec/rubocop/ast/node_spec.rb
This PR fixes the following build error when using Ruby 3.4dev:
```console
$ ruby -v
ruby 3.4.0dev (2024-02-24T04:19:37Z master e9e752c7ef) [x86_64-darwin23]
$ bundle exec rspec ./spec/rubocop/ast/node_spec.rb:322
Run options: include {:locations=>{"./spec/rubocop/ast/node_spec.rb"=>[322]}}
Randomized with seed 21659
F
Failures:
1) RuboCop::AST::Node#pure? for a regexp with no interpolation returns true
Failure/Error: let(:src) { URI::DEFAULT_PARSER.make_regexp.inspect }
NameError:
uninitialized constant URI
Finished in 0.00259 seconds (files took 0.32884 seconds to load)
1 example, 1 failure
Failed examples:
rspec ./spec/rubocop/ast/node_spec.rb:322 # RuboCop::AST::Node#pure? for a regexp with no interpolation returns true
```
=> Fix a build error

.github/workflows/rubocop.yml, .rubocop.yml, changelog/change_drop_ruby_26_runtime_support.md, lib/rubocop/ast/node.rb, rubocop-ast.gemspec
Follow up https://github.com/rubocop/rubocop-ast/pull/277#issuecomment-1962302045.
This PR drops Ruby 2.6 runtime support to prepare to support Prism.
=> Drop Ruby 2.6 runtime support

.github/workflows/rubocop.yml, Rakefile, changelog/new_support_prism.md, docs/modules/ROOT/pages/index.adoc, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec, spec/rubocop/ast/if_node_spec.rb, spec/rubocop/ast/processed_source_spec.rb, spec/rubocop/ast/range_node_spec.rb, spec/rubocop/ast/token_spec.rb, spec/rubocop/ast/traversal_spec.rb, spec/rubocop/ast/until_node_spec.rb, spec/rubocop/ast/while_node_spec.rb, spec/spec_helper.rb
This PR introduces the `parser_engine` option to `ProcessedSource` to support Prism, as part of the RuboCop AST side effort towards addressing https://github.com/rubocop/rubocop/issues/12600.
By default, analysis is performed using the Parser gem, so the default value for the newly added `parser_engine` is `parser_whitequark`:
```ruby
ProcessedSource.new(@options[:stdin], ruby_version, file, parser_engine: :parser_whitequark)
```
This code maintains compatibility, meaning the traditional behavior is preserved:
```ruby
ProcessedSource.new(@options[:stdin], ruby_version, file)
```
To perform analysis using Prism, specify `parser_engine: :parser_prism`:
```ruby
ProcessedSource.new(@options[:stdin], ruby_version, file, parser_engine: :parser_prism)
```
The parameter name `parser_prism` …
=> Support Prism as a Ruby parser

.github/workflows/rubocop.yml, Rakefile, spec/spec_helper.rb
This PR removes useless `TARGET_RUBY_VERSION` env var and uses `PARSER_ENGINE` env var instead.
In fact, the `ruby_version` in `shared_context` is replaced with the value required by `PARSER_ENGINE`:
https://github.com/rubocop/rubocop-ast/blob/49b135be4a4edce97955a1e987d50a295f72a907/spec/spec_helper.rb#L22-L60
=> Remove useless `TARGET_RUBY_VERSION` env var

Gemfile, changelog/change_remove_parser_from_runtime_dependency.md, docs/modules/ROOT/pages/index.adoc, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec
Fixes #282.
This PR removes Prism from runtime dependency.
If it is decided that Prism will not be a runtime dependency for the time being, error message and documentation will be used to communicate the dependency on Prism to users.
Making it a default runtime dependency will be avoided until at least #282 installation error with Prism is resolved.
=> [Fix #282] Remove Prism from runtime dependency

lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb
`parser` doesn't exist, it must be `parser_whitequark`. In addition, this only accepts symbols.
When passing a string, this would previously print ``The keyword argument `parser_engine` accepts `parser` or `parser_prism`, but `parser_prism` was passed.``. Use `inspect` to clearly show what you did wrong.
The new error message looks like this: ``The keyword argument `parser_engine` accepts `:parser_whitequark` or `:parser_prism`, but `"parser_prism"` was passed.``.
=> Improve error message for invalid `parser_engine` value

Gemfile
This is a workaround for incompatibilities between Prism 0.24.0 and 0.25.0. To upgrade to Prism 0.25+, it is necessary to investigate the following build error and provide feedback to Prism. I will proceed with these separately.
=> Workaround for incompatibilities between Prism 0.24.0 and 0.25.0

changelog/fix_error_for_magic_encoding_comment.md, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec, spec/rubocop/ast/processed_source_spec.rb
This specific exception has been added only in the most recent release. Previously it threw an `ArgumentError`. PR in parser: https://github.com/whitequark/parser/pull/999
This is not _really_ a syntax error: Running a file with an encoding like that produces the following output:
```
test.rb:1: unknown encoding name: foobar (ArgumentError)
```
RuboCop will report it as one though, since it will pick up the error from `parser_error`. I don't believe it is worth it to add extra logic to make a distinction here.
=> Handle encoding error from the parser gem

lib/rubocop/ast/node/array_node.rb
This PR lifts the deprecation from `ArrayNode#each_value` for the following reasons:
1. `HashNode#each_value` and `HashNode#each_key` are not deprecated.
- `HashNode#each_value` ... https://github.com/rubocop/rubocop-ast/blob/v1.31.3/lib/rubocop/ast/node/hash_node.rb#L76-L89
- `HashNode#each_key` ... https://github.com/rubocop/rubocop-ast/blob/v1.31.3/lib/rubocop/ast/node/hash_node.rb#L52-L65
2. `node.values.each` is recommended by `Style/HashEachMethods` cop to be replaced with `each_value` instead of `values.each`. And `node.each_value do |value|` is clearer in intent than `node.children.each do |value|`.
Since it is a soft deprecation in documentation only, it has not been added to the changelog.
=> Lift the deprecation from `ArrayNode#each_value`

docs/modules/ROOT/pages/node_types.adoc
Follow up https://github.com/whitequark/parser/pull/716.
The `def_e` and `defs_e` nodes representing endless method definitions no longer exist. Instead, these are represented by `def` and `defs` nodes with empty `location.end` information.
=> [Docs] Update the doc of Node Types

docs/modules/ROOT/pages/node_pattern.adoc, docs/modules/ROOT/pages/node_pattern_compiler.adoc
It's an invaluable tool when trying to understand what the hell is going on (for me at least). When googling `rubocop node pattern debugger` it's the 6th result for me, while the hackers guide is the first. I think it makes sense to link it here, and in the more detailed guide as well.
=> Link the node pattern debugger in docs

spec/rubocop/ast/node_spec.rb
Definining a method in a `before :all` block doesn't clean it up automatically, meaning once we've defined it, it's there for all remaining tests.
Since it leaks anyway, we can just define it at the top of the file, and avoid needing to disable `ConstantDefinitionInBlock`.
=> Move test `Node#used?` predicate method definition

lib/rubocop/ast.rb, lib/rubocop/ast/node/mixin/collection_node.rb, lib/rubocop/ast/node_pattern.rb, lib/rubocop/ast/node_pattern/compiler.rb, lib/rubocop/ast/node_pattern/node.rb, lib/rubocop/ast/node_pattern/parser.rb, lib/rubocop/ast/utilities/simple_forwardable.rb
Fixes [#312]
@Earlopain do you have a minute to review the PR? 🙏
=> Optimize forwarded calls

spec/rubocop/ast/node_spec.rb
This PR suppresses the following Ruby 3.4's obsoleted warning in test:
```console
$ ruby -v
ruby 3.4.0dev (2024-09-01T11:00:13Z master eb144ef91e) [x86_64-darwin23]
$ bundle exec rspec spec/rubocop/ast/node_spec.rb:320
(snip)
/Users/koic/src/github.com/rubocop/rubocop-ast/spec/rubocop/ast/node_spec.rb:320:
warning: URI::RFC3986_PARSER.make_regexp is obsoleted. Use URI::RFC2396_PARSER.make_regexp explicitly.
```
=> Suppress a Ruby 3.4's obsoleted warning in test

changelog/fix_def_node_void_context.md, lib/rubocop/ast/node/def_node.rb, spec/rubocop/ast/def_node_spec.rb
Currently, `DefNode#void_context?` incorrectly returns `true` for class methods called `initialize`. This PR fixes this.
```ruby
def initialize
42
end
def self.initialize
42
end
```
=> Fix `RuboCop::AST::DefNode#void_context?` to handle class methods called `initialize`

Gemfile
This was present all the way back when the gem was extracted but I don't think this is actually needed here.
For RuboCop, it was fixed here: https://github.com/rubocop/rubocop/pull/13071
Edit: Looks good https://github.com/rubocop/rubocop-ast/actions/runs/10753134155/job/29822235839?pr=316
=> Bump `simplecov`

Gemfile, spec/rubocop/ast/wrapped_arguments_node.rb
This PR fixes the following build failures when using Prism 1.1+.
```console
$ bundle exec prism_spec
(snip)
Failed examples:
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:2:4:1]'
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:2:1:1]'
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:2:3:1]'
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:2:2:1]'
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:2:6:1]'
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:2:5:1]'
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:1:1:1]'
rspec './spec/rubocop/ast/next_node_spec.rb[1:1:1:2:1]'
rspec './spec/rubocop/ast/break_node_spec.rb[1:1:2:5:1]'
rspec './spec/rubocop/ast/break_node_spec.rb[1:1:2:6:1]'
rspec './spec/rubocop/ast/break_node_spec.rb[1:1:2:1:1]'
rspec …
```
=> Use Prism 1.1+

lib/rubocop/ast/node/if_node.rb
From https://github.com/rubocop/rubocop/pull/13312, probably
```
$ bundle exec rubocop
Inspecting 165 files
..............................W......................................................................................................................................
Offenses:
lib/rubocop/ast/node/if_node.rb:105:45: W: [Correctable] Lint/SafeNavigationConsistency: Use . instead of unnecessary &..
else_branch&.if_type? && else_branch&.elsif?
^^
165 files inspected, 1 offense detected, 1 offense autocorrectable
```
=> Fix RuboCop offense

docs/modules/ROOT/pages/node_pattern.adoc
It's a nifty feature currently not mentioned in the docs. Hash keys can be interpolated which would then not make this match anymore but for demonstration purposes this is the best example I could come up with.
cc @dvandersluis 
Unrelated to this, I've added ruby code styling to a code block that was previously missing it.
=> Document named captures

rubocop-ast.gemspec
`check_commit.rake` requires 'English' but when doing `bundle exec rubocop` this repository this file will also be evaluated.
This also happens in the `rubocop` repository (my main motivation here) if `rubocop-ast` is in the parent folder because of this line in its Gemfile: https://github.com/rubocop/rubocop/blob/66c8276b5d9e60fed1fb8d937649c3c153e5037d/Gemfile#L29-L30
```
$ RUBYOPT=-w bundle exec rubocop -V
.../rubocop-ast/rubocop-ast.gemspec:18: warning: global variable `$RS' not initialized
1.62.1 (using Parser 3.3.0.5, rubocop-ast 1.31.2, running on ruby 3.3.0) [x86_64-linux]
- rubocop-performance 1.20.2
- rubocop-rspec 2.27.1
```
=> Fix a ruby warning when executing with `bundle exec rubocop` in this repository

.rubocop_todo.yml, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, spec/rubocop/ast/send_node_spec.rb
I noticed this when testing `Style/AccessModifierDeclarations`. When an access modifier has multiple arguments, `non_bare_access_modifier_declaration?` erroneously (IMO) returns false, which causes the cop to not recognize all cases it should.
The cop does not properly recognize (as a positive or negative, depends on the `AllowModifiersOnSymbols` configuration) this despite the examples for the cop including it.
```ruby
private :foo, :bar
```
I have a follow up PR to `Style/AccessModifierDeclarations` coming once this can be merged.
=> Allow `non_bare_access_modifier_declaration?` to handle modifiers with multiple arguments

lib/rubocop/ast/node/asgn_node.rb, lib/rubocop/ast/node/casgn_node.rb, lib/rubocop/ast/node/op_asgn_node.rb
The methods are already available for `masgn`, so this will allow all assignment node types to have the same two methods so that they can be dealt with in unison. Once released I've found some places in rubocop where more destructuring can be simplified.
Follows https://github.com/rubocop/rubocop/pull/13413#discussion_r1827267164
I didn't add tests for these aliases but am happy to if desired!
=> Introduce `lhs` and `rhs` aliases to assignment nodes for consistency.

changelog/new_extend_nodeconst_name_to_casgn_nodes.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
Now that `CasgnNode` was added in #204, we can extend `const_name` to `casgn` nodes as well. This allows code such as https://github.com/rubocop/rubocop/blob/736e8d699b5f632e7a05fd65788e28f23b2e3a67/lib/rubocop/cop/style/swap_values.rb#L84-L89 to be refactored out.
=> Extend `Node#const_name` to `casgn` nodes

changelog/new_add_nodetype_to_reduce_complexity_of.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
There are a lot of places in rubocop in which we check if a node is one of multiple node types. This allows those checks to be refactored to be less complex.
```ruby
node.call_type? || node.const_type? || node.lvar_type?
node.type?(:call, :const, :lvar)
```
This covers both the standard node type predicates, as well as the meta predicates for multiple node types (ie. `call_type?` for `send` and `csend`).
If `Node#string_type?` in #328 is accepted, I'll add that in here as well.
=> Add `Node#type?` to reduce complexity of checking against multiple node types

docs/modules/ROOT/pages/node_types.adoc
There was a stray table cell in the `masgn` row which pushed everything below it off by a cell.
=> Fix docs for `masgn`

changelog/fix_fix_331_fix_crash_in_opasgnnodename_when.md, lib/rubocop/ast/node/op_asgn_node.rb, spec/rubocop/ast/op_asgn_node_spec.rb
`OpAsgnNode#assignment_node` could be a `send`/`csend` node, but this would cause `#name` to crash as call nodes do not respond to `name`.
Fixes #331.
=> [Fix #331] Fix crash in `OpAsgnNode#name` when the lhs is a `send` or `csend` node

changelog/change_deprecate_ensurenodebody_in_favour_of.md, lib/rubocop/ast/node/ensure_node.rb, spec/rubocop/ast/ensure_node_spec.rb
Given the upcoming method change in #336, but also the fact that the tests of that PR cannot pass as-is since rubocop is still relying on the old definition, I thought it would make sense to deprecate `EnsureNode#body` and add `#branch` as an alias. Once released, I can update the uses of `EnsureNode#body` in rubocop (and extensions) without breaking anything, which will allow the "Main Gem Specs" CI to pass.
=> Deprecate `EnsureNode#body` in favour of `EnsureNode#branch`

changelog/fix_dont_emit_deprecation_just_yet.md, lib/rubocop/ast/node/ensure_node.rb
There currently is no RuboCop version that will not show this warning.
Somehow this did not cross my mind while looking at the other PR...
This can be reverted after RuboCop and its extensions are updated and released  to use the non-deprecated method.
=> Don't show a deprecation warning for `EnsureNode#branch` just yet

changelog/fix_anon_splat_for_mlhs.md, lib/rubocop/ast/node/mlhs_node.rb, spec/rubocop/ast/mlhs_node_spec.rb
Ref: https://github.com/rubocop/rubocop/issues/13505
I checked what the cop was previously expecting here, before https://github.com/rubocop/rubocop/pull/13422
I'm not sure if a `splat` makes much sense here, but nil seems even more unexpected.
cc @dvandersluis
=> Handle anonymous splats in `MlhsNode`

lib/rubocop/ast/node.rb, lib/rubocop/ast/node/array_node.rb, lib/rubocop/ast/node/for_node.rb, lib/rubocop/ast/node/hash_node.rb, lib/rubocop/ast/node/in_pattern_node.rb, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, lib/rubocop/ast/node/mixin/parameterized_node.rb, lib/rubocop/ast/node/str_node.rb, lib/rubocop/ast/node/until_node.rb, lib/rubocop/ast/node/when_node.rb, lib/rubocop/ast/node/while_node.rb, spec/rubocop/ast/node_spec.rb
Goal is to simplify the code a bit, and also insures that these predicates do not respond `nil` because of the safe navigation operator. (i.e. partly fixes #319 )
How does that look? cc @dvandersluis
=> Add `Node#loc_is?` for easier test of locations

changelog/change_add_strnodepercent_literal_to_simplify.md, lib/rubocop/ast/node/str_node.rb, spec/rubocop/ast/dstr_node_spec.rb, spec/rubocop/ast/str_node_spec.rb
This would allow rubocop code that checks for different string delimiter types to do so in a simpler way.
I took inspiration from `ArrayNode#percent_literal?` for the interface for `StrNode#percent_literal?`.
=> Add `StrNode#single_quoted?`, `StrNode#double_quoted?` and `StrNode#percent_literal?` to simplify checking for string delimiters

changelog/new_make_rubocop_ast_if_node_support_then_predicate.md, lib/rubocop/ast/node/if_node.rb, spec/rubocop/ast/if_node_spec.rb
This PR makes `RuboCop::AST::IfNode` support `then?`, similar to `RuboCop::AST::InPatternNode` and `RuboCop::AST::WhenNode`.
=> Make `RuboCop::AST::IfNode` support `then?`

lib/rubocop/ast/node/mixin/predicate_operator_node.rb, lib/rubocop/ast/token.rb
```
Offenses:
lib/rubocop/ast/node/mixin/predicate_operator_node.rb:28:9: C: [Correctable] Style/MultipleComparison: Avoid comparing a variable with multiple items in a conditional, use Array#include? instead.
operator == LOGICAL_AND || operator == LOGICAL_OR
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/ast/node/mixin/predicate_operator_node.rb:35:9: C: [Correctable] Style/MultipleComparison: Avoid comparing a variable with multiple items in a conditional, use Array#include? instead.
operator == SEMANTIC_AND || operator == SEMANTIC_OR
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/ast/token.rb:86:9: C: [Correctable] Style/MultipleComparison: Avoid comparing a variable with multiple items in a conditional, use Array#include? instead.
type == :tLCURLY || …
```
=> Fix current RuboCop offenses

.github/workflows/rubocop.yml
Ruby 3.4 has been released, and support for Ruby 3.4.0 and 3.4.1 was added to setup-ruby: https://github.com/ruby/setup-ruby/pull/679
https://github.com/rubocop/rubocop/pull/13297 is required to pass the following spec on both Ruby versions before 3.3 and 3.4 and later:
```console
1) RuboCop::ConfigStore.for always uses config specified in command line
Failure/Error: expect(config_store.for('file1')).to eq('merged {:options_config=>true}')
expected: "merged {:options_config=>true}"
got: "merged {options_config: true}"
(compared using ==)
```
https://github.com/rubocop/rubocop-ast/actions/runs/12529029565/job/34944210256
Therefore, RuboCop used in `rubocop_specs` has been updated to v1.69.2, the version released with Ruby 3.4.
=> CI against Ruby 3.4

lib/rubocop/ast/processed_source.rb
There are two different cases that may happen:
Prism was compiled in the past, the user updated the ruby version, but it still points to the same library
> linked to incompatible /home/user/.rbenv/versions/3.4.1/lib/libruby.so.3.4 - /home/user/Documents/ruby-prism/lib/prism/prism.so
In that case, bubble up the original error.
On the other hand, since prism is no dependency, users may run older verions that are missing translator classes. In that case, show a message what they should do.
prism is a default gem since 3.3, so you can even use it without adding it to your gemfile.
=> Better handle `LoadError`s from prism

.github/workflows/rubocop.yml
1.69.2 was only just recently released. Since 3.4 changed hash inspect formatting, some specs now fail.
Instead, bump the ruby version against rubocop master which is equiped to handle these changes.
Now it again tests against a version that is about one year old. 1.61 is the minimum because of https://github.com/rubocop/rubocop-ast/pull/296
=> CI against an older RuboCop version

.github/workflows/rubocop.yml, .github/workflows/spell_checking.yml
Let's see if I got this right on the first try :upside_down_face: (I didn't)
A few months ago I and @\bquorning made some tweaks to rubocops CI. This imports some of that work, and does a bit specific to this repo.
I made a handful of individual commits explaining why I did something for each. Overall the workflow files lost a bit of weight and are easier to follow.
=> Clean up CI a bit

changelog/change_allow_groups_for_traversal.md, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/args_node.rb, lib/rubocop/ast/node/mixin/descendence.rb, spec/rubocop/ast/node_spec.rb
Sometimes it would be nice to do `each_child_node(:call)` instead of `each_child_node(:send, :csend)`. This nicely mirrors that you can already use these aliases when writing node patterns
=> Support node groups in `Node#each_descendant` and similar traversal methods

changelog/fix_captures_in_repetition.md, lib/rubocop/ast/node_pattern/node.rb, spec/rubocop/ast/node_pattern_spec.rb
Fix https://github.com/rubocop/rubocop-ast/issues/323
The calculation for how many captures a pattern has was not correct in this case. A pattern like `(send _ _ (int {$_ | $_ | 
$_})?)` would end up with 3 captures, even though the union would in total only contribute one
=> [Fix #322] Fix node captures inside of `?`, `+`, and `*` repetition

changelog/new_group_block.md, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/mixin/method_dispatch_node.rb
There are many instances where you just want to know if it's a block and don't care about what type it is: https://github.com/search?q=org%3Arubocop+%2Fblock.*numblock%2F&type=code
Should `itblock` be added, most of these will need to add yet another block type. With this, they can instead use this.
I had a bit of trouble choosing a good name. Maybe you have a better one to use?
=> Add `Node#any_block_type?` to determine if a node is either a block or numblock

changelog/fix_array_writer_method.md, lib/rubocop/ast/utilities/simple_forwardable.rb, spec/rubocop/simple_forwardable_spec.rb
Fix #360
This is a syntax error:
```
def foo=(...)
end
```
So it must use `public_send` instead in that case. It's caused by https://github.com/rubocop/rubocop-ast/blob/47e0eead4b84c3d28d7251a548e152f914219773/lib/rubocop/ast/node/mixin/collection_node.rb#L9-L10
By default the `Array` class doesn't contain such methods but when something like spring is in use, code can be evaluated before rubocop.
I thought about simply rejecting such methods but supporting it is easy enough
=> [Fix #360] Fix an error when the `Array` core class contains a writer method

lib/rubocop/ast/traversal.rb
I had a bit of trouble following how this code actually works.
I find the argument names to be unfortunatly named. When I see signature/arity, I think of methods. But it actually refers to the structure of child nodes here.
There also was the `arity_check` argument, which isn't necessary. Reusing the arity with a endless range makes it a bit simpler.
=> Modify `def_callback` code to be easier to understand

changelog/change_prism_builder.md, lib/rubocop/ast/builder.rb, lib/rubocop/ast/builder_prism.rb, lib/rubocop/ast/processed_source.rb
Context: https://github.com/ruby/prism/pull/3443
I'd like for prism to emit ast for new ruby features, like `it`. It's incredibly easy for prism to emit `itblock`, it just needs a custom builder, with a few lines changed to do so. But since `rubocop-ast` already uses its own custom builder, they need to play nicely together for it to work.
The PR for prism just adds the builder class, without any changes. I'd like to explore that after this.
=> Prism custom builder

lib/rubocop/ast/node/ensure_node.rb
Adds the deprecation warning for `EnsureNode#branch` back now that it's fixed in @rubocop, as suggested by @Earlopain.
This is the next step in being able to merge #336.
Reverts rubocop/rubocop-ast#339
See https://github.com/rubocop/rubocop-ast/pull/339#issuecomment-2737067996
=> Revert "Don't show a deprecation warning for `EnsureNode#branch` just yet"

changelog/new_support_itblock.md, docs/modules/ROOT/pages/node_types.adoc, lib/rubocop/ast/builder.rb, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/block_node.rb, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, lib/rubocop/ast/traversal.rb, rubocop-ast.gemspec, spec/rubocop/ast/block_node_spec.rb, spec/rubocop/ast/node_spec.rb, spec/rubocop/ast/send_node_spec.rb, spec/rubocop/ast/traversal_spec.rb, spec/spec_helper.rb
In tests, prism will always be used for Ruby 3.4+ and tests that don't pass with `parser` get marked as broken.
Needs https://github.com/whitequark/parser/pull/1071, draft for now. The minimum parser version _must_ be bumped in this PR, as otherwise `itblock_type?` method is not available.
=> Add support for `itblock` node for Ruby 3.4

lib/rubocop/ast/node_pattern/compiler/debug.rb, spec/rubocop/ast/node_pattern_spec.rb
It emits a deprecation warning on Ruby 3.4 and won't support new versions. Instead:
* In tests use a fixed version that can be changed if needed
* Delegate to `ProcessedSource` and `RUBY_VERSION` to do the right thing. Eventually this will use the prism translation automatically
=> Stop using `Parser::CurrentRuby`

spec/rubocop/ast/fixtures/code_examples.rb, spec/rubocop/ast/if_node_spec.rb, spec/rubocop/ast/processed_source_spec.rb, spec/rubocop/ast/token_spec.rb, spec/rubocop/ast/traversal_spec.rb, spec/rubocop/ast/until_node_spec.rb, spec/rubocop/ast/while_node_spec.rb
These all just pass now.
The traversal spec is a bit special. With `parser`, Ruby 2.7 is used but `prism` can only do 3.3. So some code samples are now invalid syntax on newer rubies. I simply removed those.
=> Remove prism skips in tests

changelog/new_support_ruby35.md, docs/modules/ROOT/pages/index.adoc, lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb, spec/spec_helper.rb
One step further towards https://github.com/rubocop/rubocop/issues/13617
In RuboCop, the parser engine in the default config can be set to `default`, and  with Ruby 3.5, RuboCop will then automatically choose prism to do its job.
More discussion and considerations in https://github.com/rubocop/rubocop-ast/pull/371
=> Support `Prism::Translation::Parser35` for Ruby 3.5 parser

Gemfile, changelog/change_prism_runtime_dep.md, docs/modules/ROOT/pages/index.adoc, lib/rubocop/ast.rb, lib/rubocop/ast/processed_source.rb, rubocop-ast.gemspec, spec/rubocop/ast/processed_source_spec.rb
RuboCop is starting to rely on it to parse ruby versions that the parser gem doesn't support.
This absolves the user from declaring the dependency themselves.
Bits and pieces I removed from https://github.com/rubocop/rubocop-ast/pull/370
=> Add `prism` as a dependency

changelog/change_prism_ruby_3.4.md, docs/modules/ROOT/pages/index.adoc, lib/rubocop/ast/processed_source.rb, spec/rubocop/ast/processed_source_spec.rb
The parser gem doesn't actually support any of the Ruby 3.4 syntax changes.
Builds on top of https://github.com/rubocop/rubocop-ast/pull/373
=> Use the prism translation layer to analyze Ruby 3.4 by default 

changelog/new_support_any_def_type_predicate.md, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/mixin/method_dispatch_node.rb
This PR adds support for `RuboCop::AST::Node#any_def_type?` method, which abstracts over the `def` and `defs` node types.
=> Add support `RuboCop::AST::Node#any_def_type?` method

changelog/new_add_any_match_pattern_type_p_to_ast_node.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
This PR adds `AST::Node#any_match_pattern_type?`.
This method can be used to simplify multiple places where `node.type?(:match_pattern, :match_pattern_p)` is used, such as in the changes made in https://github.com/rubocop/rubocop/pull/14224.
=> Support `AST::Node#any_match_pattern_type?` method

changelog/new_add_nodeany_sym_type_to_match_sym_and.md, lib/rubocop/ast/node.rb, spec/rubocop/ast/node_spec.rb
Following #328, adds `any_sym_type?` to match `sym` and `dsym` nodes.
=> Add `Node#any_sym_type?` to match `sym` and `dsym` types
